# Generated by Django 4.2.9 on 2024-01-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_category_id_alter_comment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="profession",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
