# Generated by Django 4.2.9 on 2024-01-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_prompt_description_alter_prompt_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt", name="like", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="prompt", name="un_like", field=models.IntegerField(null=True),
        ),
    ]
