# Generated by Django 4.2.9 on 2024-01-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_professionmap_profession_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymap",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="professionmap",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
