# Generated by Django 4.2.9 on 2024-01-04 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_categorymap_id_alter_professionmap_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymap",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="core.prompt",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.prompt",
            ),
        ),
        migrations.AlterField(
            model_name="professionmap",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="professionmap",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professions",
                to="core.prompt",
            ),
        ),
    ]
