# Generated by Django 4.2.9 on 2024-01-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_categorymap_prompt_alter_comment_prompt_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="prompt", ),
        migrations.RemoveField(model_name="commentmap", name="comment_id", ),
        migrations.RemoveField(model_name="commentmap", name="prompt_id", ),
        migrations.AddField(
            model_name="commentmap",
            name="comment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.comment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="commentmap",
            name="prompt",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="core.prompt",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commentmap",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
