# Generated by Django 4.2.9 on 2024-01-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_platform_tag_delete_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tag", name="name", field=models.CharField(max_length=255),
        ),
    ]
