# Generated by Django 4.2.9 on 2024-01-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_platform_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profession",
            name="created_at",
            field=models.DateTimeField(auto_now=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="created_at",
            field=models.DateTimeField(auto_now=True, auto_now_add=True),
        ),
    ]
