# Generated by Django 4.2.9 on 2024-01-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_category_update_at_comment_update_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="in_put",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prompt",
            name="out_put",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
